#Requires -Version 7
# devbase-claude.ps1 — ClaudeCode launcher with devbase Project Brief injection
# v0.18.0

param(
    [string]$RepoId = "",
    [switch]$SkipBrief,
    [switch]$CaptureOnExit
)

$ErrorActionPreference = "Stop"

# 1. Resolve repo_id from current directory if not provided
if (-not $RepoId) {
    $cwd = (Get-Location).Path
    # Try to get repo_id from devbase registry by matching local_path
    $repoJson = devbase query repos --json 2>$null | ConvertFrom-Json -ErrorAction SilentlyContinue
    if ($repoJson) {
        $match = $repoJson | Where-Object { $cwd -like "*$($_.local_path)*" -or $cwd -like "*$($_.id)*" } | Select-Object -First 1
        if ($match) {
            $RepoId = $match.id
            Write-Host "[devbase] Detected repo: $RepoId" -ForegroundColor Cyan
        }
    }
}

# 2. Generate Project Brief and inject into .claude/CLAUDE.md
if ($RepoId -and -not $SkipBrief) {
    Write-Host "[devbase] Generating project brief for $RepoId ..." -ForegroundColor Cyan
    $brief = devbase project brief --repo-id $RepoId --max-tokens 3000 2>$null | ConvertFrom-Json -ErrorAction SilentlyContinue
    if ($brief -and $brief.brief) {
        $claudeDir = Join-Path (Get-Location) ".claude"
        if (-not (Test-Path $claudeDir)) {
            New-Item -ItemType Directory -Path $claudeDir | Out-Null
        }
        $claudeMd = Join-Path $claudeDir "CLAUDE.md"
        $header = "# Devbase Project Brief (auto-generated)\n\n> This file is automatically generated by devbase-claude.ps1.\n> Do not edit manually — run `devbase-claude.ps1 -SkipBrief` to skip regeneration.\n\n"
        $content = $header + $brief.brief
        Set-Content -Path $claudeMd -Value $content -Encoding UTF8
        Write-Host "[devbase] Injected brief into .claude/CLAUDE.md ($($content.Length) chars)" -ForegroundColor Green
    } else {
        Write-Warning "[devbase] Failed to generate brief. Proceeding without injection."
    }
}

# 3. Launch ClaudeCode
Write-Host "[devbase] Starting ClaudeCode ..." -ForegroundColor Cyan
& claude @args

# 4. Post-session capture (optional)
if ($CaptureOnExit -and $RepoId) {
    Write-Host "`n[devbase] Capturing session summary ..." -ForegroundColor Cyan
    $diff = git diff --stat HEAD 2>$null
    if ($diff) {
        $summary = "Session changes:`n$diff"
        $activeCtx = $env:DEVBASE_ACTIVE_CONTEXT
        if (-not $activeCtx) { $activeCtx = $RepoId }
        devbase session capture $activeCtx "decision" $summary 2>$null | Out-Null
        Write-Host "[devbase] Captured to context '$activeCtx'" -ForegroundColor Green
    } else {
        Write-Host "[devbase] No git changes detected — nothing to capture." -ForegroundColor DarkGray
    }
}
